version: '3'

services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=tms
      - MYSQL_DATABASE=tms
      - MYSQL_USER=tms
      - MYSQL_PASSWORD=tms
    networks:
      - tms
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - tms
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL="mysql://tms:tms@db:3306/tms"
networks:
  tms:

volumes:
  db_data:
