version: '3'

services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tms
      - MYSQL_DATABASE=tms
      - MYSQL_USER=tms
      - MYSQL_PASSWORD=tms
    networks:
      - tms
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./sys/etc/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
    env_file:
      - app/.env
    restart: always
    networks:
      - tms
    ports:
      - "9001:80"
networks:
  tms:

volumes:
  db_data:
